language: go

go:
  - 1.9
  - master

install:
  - go get -t ./...

script:
  - go build -v

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master


notifications:
  email:
    on_success: never
    on_failure: always
