language: go

go:
  - 1.9
  - master

install:
  - go get -t ./...

script:
  - go build -v

after_deploy:
  - "curl -H 'Content-Type: application/json' -X POST -d '{\"token\":\"$DEPLOY_TOKEN\"}' http://jaggernaut.ca:9000/hooks/deploy-respecbot-webhook"
