language: go

go:
  - 1.9
  - master

install:
  - go get -t ./...

jobs:
  include:
    - stage: compile
      go:
        - 1.9
        - master
      script: go build -v
    - stage: deploy
      go: 1.9
      deploy:
        provider: script
        script: scripts/deploy.sh
        on:
          branch: master

stages:
  - compile
  - name: deploy
    if: branch = master

notifications:
  email:
    on_success: never
    on_failure: always
