language: go

go:
  - 1.9

before_script: go get -t ./...

script: go build -v

jobs:
  include:
    - stage: deploy
      script: skip
      deploy:
        provider: script
        script: sh $TRAVIS_BUILD_DIR/scripts/deploy.sh
        on:
          branch: master

stages:
  - test
  - name: deploy
    if: branch = master

notifications:
  email:
    on_success: never
    on_failure: always
    on_error: always
